### PR TITLE
Nullable async results

### PR DESCRIPTION
**Pull request by witur**
inspired by https://github.com/vert-x3/vertx-lang-kotlin/issues/116 and https://github.com/vert-x3/vertx-redis-client/pull/116/files

### CODE REVIEW

**Comment by witur** [comment]
this change was inspired by https://github.com/vert-x3/vertx-lang-kotlin/issues/116 and https://github.com/vert-x3/vertx-redis-client/pull/116/files

**Comment by vietj** [comment]
@karianna impact will be in the generated classes for RxJava and Kotlin

can you backport this to 3.6 branch and reference it in https://github.com/vert-x3/issues/issues/435 ?

**Comment by vietj** [comment]
actually I did reference in the umbrella to keep track of it for 3.6.3

**Comment by vietj** [comment]
you still need to do the back-port :-)

**Comment by tsegismont** [comment]
@witur can you please update the issue description? What was your problem? The rxified API returning `Single` instead of `Maybe`? Thank you

**Comment by tsegismont** [comment]
@witur please ignore my previous comment, I had not seen the conversation

**Comment by johnoliver** [comment]
Looks good to me

**Comment by vietj** [comment]
can you backport this to 3.6 @karianna and add it to the umbrella issue as well ?

**Comment by karianna** [comment]
backport PR https://github.com/vert-x3/vertx-mongo-client/pull/170 - I'll preemptively add it to the umbrella

**Comment by vietj** [comment]
+1

**Pull request merged**
