### PR TITLE
Extended JSON Support for Timestamp

### PR DESCRIPTION
**Pull request by MazizEsa**
1. Added timestamp extended json support.
2. Added test for the timestamp extended json support. #51

### CODE REVIEW

**Comment by MazizEsa** [comment]
@karianna @vietj hi guys. Please review when you got time. Thanks.

**Comment by cescoffier** [comment]
It's better if @johnoliver or @karianna can review this one, they are the maintainers of this module.

**Comment by karianna** [comment]
Good clean code.  CLoses #51

**Comment by vietj** [comment]
@MazizEsa have you signed the contributor CLA ?

**Comment by karianna** [comment]
I don't think he needs to as this module isn't part of the Eclipse
foundation?  Do correct me if I'm wrong though!

Cheers,
Martijn

**Comment by vietj** [comment]
it needs CLA sign but not commits to be sign-off for non eclipse projects : https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md

**Comment by karianna** [comment]
Argh, so sorry @MazizEsa can you sign the CLA please?

**Comment by MazizEsa** [comment]
@vietj @karianna dont worry. I did my homework. Signed before taking the issue already :) Thanks. Ill pick another few more tickets for mongo-client.

**Comment by vietj** [comment]
thanks for the contribution @MazizEsa just wanted to check and I did not see your email on your github account.

**Pull request merged**
