### PR TITLE
JSON config takes precedence over connection string

### LINKED ISSUE #243: Config Parsing is out of order
### Version

4.0.0

### Context

I was parsing json/JsonObject with MongoClientOptionsParser.

### Steps to reproduce

1.            var parsing : MongoClientOptionsParser = MongoClientOptionsParser(vertx, JsonObject(mongoConfigJson))
2. Input Json: core: {
  mongo:{
    db_name: "mydb"
    connection_string: "mongodb://localhost:27017"
    maxPoolSize: 10
    minPoolSize: 3
  }
}
3. maxPoolSize is ignored.

### Extra

The source code below, only considers connection_string. It should almost certainly parse all the other values *first*, then apply the connection_string. That would allow one to set individual values in a readable way. While overriding them with values from the connection_string. I guess you could just remove the else, and allow the individual settings to override anything parsed from the connection_string.

But, as-is, you can't really have connection_string *and* any other settings.

  public ConnectionPoolSettingsParser(ConnectionString connectionString, JsonObject config) {
    ConnectionPoolSettings.Builder settings = ConnectionPoolSettings.builder();
    if (connectionString != null) {
      settings.applyConnectionString(connectionString);
    } else {
      Integer maxPoolSize = config.getInteger("maxPoolSize");
      if (maxPoolSize != null) {
        settings.maxSize(maxPoolSize);
      }

### PR DESCRIPTION
**Pull request by tsegismont**
Closes #243

This is a breaking change from configuration standpoint.

### CODE REVIEW

**Comment by tsegismont** [comment]
@vietj please review but don't merge until `master` branch targets 4.1

**Comment by vietj** [comment]
Can you describe in the commit message what the commit changes to achieve the desired effect ?

**Comment by vietj** [comment]
Set fix version to 4.1 to signal it is not for 4.0.x

**Comment by tsegismont** [comment]
The fix version is not needed here given this PR will close an issue that has the version set. Otherwise, we'd have a duplicate in the release notes.

I've amended the commit message.

**Comment by tsegismont** [comment]
@vietj can you please take another look?

**Comment by vietj** [comment]
should this be considered as a breaking change ?

**Comment by tsegismont** [comment]
@vietj ok to merge?

**Pull request merged**
