### PR TITLE
Read file gridfs into ReadStream

### PR DESCRIPTION
**Pull request by liuchong**
Motivation:

Sometimes we need only a ReadStream, no need to write to a file.

### CODE REVIEW

**Comment by liuchong** [comment]
Please check if we need this @vietj @pmlopes @tsegismont , I will add some unit test and do more code optimization if it will merge, thanks!

**Comment by tsegismont** [comment]
Thank you @liuchong , I'll review it

**Review by tsegismont — COMMENTED** [review]
Thank you @liuchong , can you please add some tests?

**Comment by liuchong** [comment]
Ok, sorry for the delay, I will add tests in my tomorrow morning 👀

**Comment by tsegismont** [comment]
No worries, thank you!

**Review by tsegismont — APPROVED** [review]
LGTM, thank you @liuchong !

**Pull request merged**
