### PR TITLE
Fix #296 Compressors config didn't work

### LINKED ISSUE #296: Compression settings don't work.
### Questions

Compression settings don't work.

### Version

4.3.2

### Context

```java
        JsonObject config = new JsonObject();
        config.put("connection_string", "mongodb://root:root@127.0.0.1:37171,127.0.0.1:37172/?compressors=snappy")
            .put("useObjectId", true)
            .put("compressors", "snappy")
            .put("waitQueueTimeoutMS", Duration.ofDays(1).toMillis())
            .put("maxIdleTimeMS", 200000)
            .put("db_name", "statistic")
            .put("maxPoolSize", 6)
            .put("minPoolSize", 1);

        mongoClient = MongoClient.create(vertx, config);
        return mongoClient;
```
`compressors=snappy` does't work.

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

### PR DESCRIPTION
**Pull request by tarvfx**
Motivation:

Fix #296: Compressors config didn't work

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by tsegismont** [comment]
Thank you @tarvfx 

Do you plan to add the documentation and connectivity test with zlib later? We plan to release 4.4 early next week.

**Comment by tarvfx** [comment]
Hi, @tsegismont 

Thanks for helping me improve the PR. ☕

Happy to follow up, but how do I do the connectivity test? I've used the fix in production and it works fine.

Documentation may need your help (I can try to do it). Because English is not my first language😂.

`snappy` and `zstd` depend on third-party artifacts. Do we need to add dependencies (provided scope) in `pom.xml`?
```xml
  <dependency>
    <groupId>com.github.luben</groupId>
    <artifactId>zstd-jni</artifactId>
    <version>1.5.4-1</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>org.xerial.snappy</groupId>
    <artifactId>snappy-java</artifactId>
    <version>1.1.9.1</version>
    <scope>provided</scope>
  </dependency>
```

**Comment by tsegismont** [comment]
> how do I do the connectivity test?

You can create a test which extends `MongoTestBase` in `src/test/java/io/vertx/ext/mongo`
The test shall verify that you can connect and make a query using zlib compression.



> Documentation may need your help (I can try to do it). Because English is not my first languagejoy.

Sure, you shall edit the `src/main/asciidoc/index.adoc` file.
You can add a new subsection titled _Network compression configuration_

> 
> `snappy` and `zstd` depend on third-party artifacts. Do we need to add dependencies (provided scope) in `pom.xml`?

No, but you shall explain in the doc that users must add these artifacts to their dependencies if they want to support the corresponding compression algorithm.

**Comment by tarvfx** [comment]
Hi, @tsegismont 

I submitted connectivity tests and documentation. Please review, thanks!

Regards,

**Review by tsegismont — APPROVED** [review]
Thank you @tarvfx , this looks good to me

**Pull request merged**
