### PR TITLE
add client ssl authentication

### PR DESCRIPTION
**Pull request by zyclonite**
* update credential option parser to support x509 without username
* refactor caPath to support certificate chains as well
* add keyPath and certPath
* refactor ssl impl to use vertx ssl helpers
* update docs and tests

### CODE REVIEW

**Comment by karianna** [comment]
@johnoliver - We've not added this functionality before, I'm more or less happy with the implementation (although it changes the core signature of the starting point).

**Comment by zyclonite** [comment]
let me know your ideas, i can try it out

**Comment by zyclonite** [comment]
@karianna @johnoliver 
any chance to help finding a way forward?

**Comment by zyclonite** [comment]
@karianna any news?

**Comment by karianna** [comment]
@johnoliver - let's try to find some time this week (timezones are hard :-))

**Comment by zyclonite** [comment]
@karianna would it make sense to merge it for 3.x ? in 4.x the signature did anyway change after migrating to the new mongo client lib and so require refactoring that pr

**Comment by karianna** [comment]
@zyclonite I'm not sure if there's going to be another 3.8.x release.  Might be worth raising a separate PR against 4.0.x

**Comment by zyclonite** [comment]
i will have a look into it, if it's similar (signature wise) it would still be good to have and idea how you like it to be so i will not invest already too much time

**Comment by zyclonite** [comment]
@karianna i did not find the time yet but now there is another "non 4.x" release, so i guess it will still take a while for the 4.x releases

**Comment by karianna** [comment]
@zyclonite Unfortunately we will not be releasing any further updates to the 3.8 series.  Please do raise a PR against master :-)

**Pull request closed without merging**
