### PR TITLE
added support for updates with aggregation pipelines (#236)

### PR DESCRIPTION
**Pull request by bfreuden**
First proposal for issue/enhancement #236.

### CODE REVIEW

**Comment by vietj** [comment]
The commit message should also mention that it fixes https://github.com/vert-x3/vertx-mongo-client/issues/253

**Comment by bfreuden** [comment]
@vietj Can you please help me? I don't know how to fix the validation error.
Here is what I've done:

I first amended the commit message (to include the ticket number) then pushed to my github repo:
`git commit --amend -m "bump MongoDB version to 4.2.1 (#253) and added support for updates with aggregation pipelines (#236)"`
`git push --force-with-lease origin enhancement-236`

As a result I got this PR validation error:
>  eclipsefdn/eca - The author(s) of the pull request is not covered by necessary legal agreements

Then I realized that I've used my corporate git author settings.
So I amended the commit (with my personal email, the one used in my Eclipse Foundation account) and pushed it once again:
`git commit --amend --author="Firstname Lastname <email of my Eclipse Foundation account>"`
`git push --force-with-lease origin enhancement-236`

But I get the same validation error (maybe it is unrelated to the email though... since using my corporate git settings has not been a problem for a previous Vert.x PR 1 or 2 months ago).

**Comment by vietj** [comment]
can you provide a new PR instead of this one ?

**Comment by bfreuden** [comment]
@vietj yes, the second PR is here #254

**Comment by bfreuden** [comment]
This PR can be closed/rejected: it is replaced by PR #254

**Pull request closed without merging**
