### PR TITLE
Migration of future API

### PR DESCRIPTION
**Pull request by tsegismont**
In addition to the migration:
- the dependency on Vert.x RS has been removed
- the Publisher / Future adapters have been reworked to avoid using wrapped callbacks

### CODE REVIEW

**Comment by zenios** [comment]
Its amazing how things are simplified when methods are promisified

Good job @tsegismont

**Comment by tsegismont** [comment]
Thanks for taking a look @zenios !

**Comment by zenios** [comment]
If i am not mistaken i added some context test when we were migrating to
mongo reactive streams. Not sure if they cover all the cases though

**Comment by vietj** [comment]
ok, we don't need to cover it all of them but some is nice.

**Comment by tsegismont** [comment]
@zenios @vietj @johnoliver ok to merge?

**Comment by zenios** [comment]
Looks OK with me

The only missing piece as @vietj already said is some tests to cover the
context is correct in some cases

Will try to add some this week.

Thanks

**Comment by tsegismont** [comment]
@zenios this would be great!

**Pull request merged**
