### PR TITLE
remove aggregate maxTimeMS option

### PR DESCRIPTION
**Pull request by bsa01**
sorry have to remove this option as running tests with it resulted in MongoDB error:
"maxTimeMS can only be used with getMore for tailable, awaitData cursors"

As an alternative I can also set the default to 0 if this is preffered.

### CODE REVIEW

**Comment by karianna** [comment]
Which version of the Mongo driver are you using?

**Comment by bsa01** [comment]
We are using 3.6.3

**Comment by karianna** [comment]
@bsa01 - Can you rebase this PR?

**Comment by karianna** [comment]
Superseded by #209

**Pull request closed without merging**
