### PR TITLE
Re-generate groovy code based on changes to vertx-lang-groovy.

### PR DESCRIPTION
**Pull request by sfitts**
Since the generation template has changed we need to generate new code.  I've also added a test for the runtime behavior which the generation change was designed to address -- retrieval of a JSON document with a nested document and array.

Signed-off-by: Sean Fitts <smfitts@gmail.com>

### CODE REVIEW

**Comment by sfitts** [comment]
Recreated #18 with signed commit.

**Comment by sfitts** [comment]
@purplefox @vietj status on getting this merged? (it is related to the recently merged lang-groovy changes)

**Comment by purplefox** [comment]
As a general principle we don't add non Java tests into APIs that are codegen'd.

One of the reasons for doing codegen in the first place is so that we can maintain the api solely in Java and have some Java tests. Once we start adding language specific tests that starts to defeat the purpose.

Any functionality that is codegenable should have corresponding tests in the vertx-lang-groovy project, so we should be confident that this stuff is tested already.

**Comment by sfitts** [comment]
@purplefox While I understand that (and did add the requisite tests to lang-groovy, I felt that the test here was useful as well.  It tests the interactions between the Mongo codec (which is specific to this project) and the code generation that is specific to this project.  This is what uncovered the underlying issue in the first place.  I'm not sure how to a) contine to test this and b) do it in lang-groovy without putting essentially this entire project into lang-groovy (whcih I'm assuming isnt' what you want).

However, if you feel strongly about it I'll remove the offending test (reducing test coverage is never a good plan IMO, but I'm just a guest here).

**Comment by sfitts** [comment]
Removed the Groovy specific test.

**Comment by purplefox** [comment]
It seems to me this PR is purely generated code now, in which case I can just regenerate and push it here, so no need for a PR :)

**Comment by sfitts** [comment]
Works for me.  Wasn't sure how you handled that.

**Pull request closed without merging**
