### PR TITLE
Implemented ISODate as it works with MongoDB since the JVM timezone i…

### PR DESCRIPTION
**Pull request by pmlopes**
…mplmentation is not 100% compatible with the ISO8601

Signed-off-by: Paulo Lopes <paulo@mlopes.net>

Test cases added which covers issue #20

### CODE REVIEW

**Comment by pmlopes** [comment]
This is not correct

**Comment by pmlopes** [comment]
All tests passing. This is a manual parser of isodates that complies to the w3c spec and is less strict with timezone formats that the JVM implementation

**Comment by pmlopes** [comment]
the issue here is that the JDK date parser does not follow the strict ISO for date formats and mongo allows almost all variations of the ISO.

Due to this all miss parses of dates from the JDK tend to be seem as a bug. In this specific case the problem was the TZ that the JDK always expects to be in [+|-]HH:MM but the ISO states that the colon is optional.

We can fix the issue with my code where i've a more compatible parser or close it stating that dates MUST be in a format that the JDK can parse.

I'd suggest a small discussion on how to tackle this.

What do you guys @purplefox, @viet, @cescoffier think?

**Comment by aesteve** [comment]
Hi Paulo, I've just read you had trouble with ISO dates, not sure it's relevant, but for ISO 8601 I used [this](https://github.com/aesteve/vertx-nubes/blob/master/src/main/java/com/github/aesteve/vertx/nubes/utils/DateUtils.java#L33-L50)


Maybe it could be interesting for you ? Not sure since I'm not a Mongo expert, but just in case :)

**Pull request closed without merging**
