### PR TITLE
Bump MongoDB Async Driver to version 3.6.3

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by karianna** [comment]
@oscerd merge conflicts, please rebase and resubmit.

**Comment by oscerd** [comment]
Done :-)

**Comment by karianna** [comment]
@vietj If I merge this will it go into 3.5.1 or 3.5.x?

**Comment by oscerd** [comment]
There is already 3.6.3 out now.

**Comment by vietj** [comment]
@karianna that will go in 3.6.x

**Comment by karianna** [comment]
@oscerd Please update the PR with 3.6.3 and I'll merge, thanks!

**Comment by oscerd** [comment]
Done :-)

**Comment by karianna** [comment]
@oscerd I think all of that ASCIIDOC versioning gets code generated - @vietj Is that correct?

**Comment by oscerd** [comment]
I just run an mvn clean install after updating the code

**Comment by oscerd** [comment]
https://github.com/vert-x3/vertx-kafka-client/commit/ccffc92fff72d1ff5ba6cbca8b87534370188530

here the docs generated were merged. So I guess is safe to merge this PR.

**Pull request merged**
