### PR TITLE
Insert many support

### PR DESCRIPTION
**Pull request by llfbandit**
support for mongo insertMany() #58

### CODE REVIEW

**Comment by karianna** [comment]
Looks good to me, high quality PR, kudos. @johnoliver anything I missed?

**Comment by amannocci** [comment]
Hi, any updates ?

**Comment by johnoliver** [comment]
The merge of the find one PR has caused some import conflicts here. Happy to merge once those are done. Thanks for the contributions

**Comment by karianna** [comment]
@llfbandit looks like there are still some conflicts remaining.

**Comment by karianna** [comment]
@llfbandit - I'll leave this open for another week then close as out of date.

**Pull request closed without merging**
