### PR TITLE
Update index.adoc (Java)

### PR DESCRIPTION
**Pull request by davidaparicio**
Change remove->removeDocuments, removeOne->removeDocument
Because remove & removeOne are deprecated

### CODE REVIEW

**Comment by davidaparicio** [comment]
Add regenerate the official documentation (http://vertx.io/docs/vertx-mongo-client/java/#_removing_documents / http://vertx.io/docs/vertx-mongo-client/java/#_removing_a_single_document)

**Comment by cescoffier** [comment]
Isn't it the `package-info.java` file that need the fix ? The index.adoc is generated no ?

**Comment by karianna** [comment]
Right you are, I'll fix at source, PR coming shortly.

**Comment by karianna** [comment]
Hopefully #87 does the trick

**Comment by cescoffier** [comment]
Yes it does. See my comment on this PR.

**Pull request merged**
