### PR TITLE
add trustAll and caPath option

### PR DESCRIPTION
**Pull request by zyclonite**
add a vertx compatible option to trust all certificates setting an empty trust store in the ssl context

### CODE REVIEW

**Comment by karianna** [comment]
@johnoliver - Do we want to do this from a security standpoint?

**Comment by zyclonite** [comment]
i would see this as the first step to have that option, the next would be to define one or a list of trusted ca certs

**Comment by zyclonite** [comment]
any update?

**Comment by vietj** [comment]
@karianna can this be reviewed and merged today to target 3.7.1 ?

**Comment by karianna** [comment]
Have asked @johnoliver to review from a philosophical level - I'm not sure it's safe to be doing this.

**Comment by johnoliver** [comment]
I believe it should be fine as users that explicitly use that option should know the implications of what they are doing. Only thing on that front is maybe we should log a warning if they use this option. There does need to be documentation and warnings in blob/master/src/main/asciidoc/index.adoc though to make this clear.

**Comment by karianna** [comment]
@zyclonite Can you make the changes as @johnoliver suggests?  I suspect if you want it in the 3.7.1 line that you'll need to create a separate PR for that as well.

**Comment by johnoliver** [comment]
I have added what I think is correct doc in #192 https://github.com/vert-x3/vertx-mongo-client/pull/192/commits/1c625abacd9dffa3e77bbea517f901d10fb4e847

So we can merge this, then #192

**Comment by zyclonite** [comment]
#193 should merge on 3.7 now

**Pull request merged**
